version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4200:4200"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ng serve --host 0.0.0.0 --poll=1000