version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./app/src:/app/src
    ports:
      - "4201:4201"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        ng serve --host 0.0.0.0 --port 4201 --disable-host-check true --poll=1000